server:
  port: 8083
  servlet:
    context-path: /kettle-scheduler

logging:
  file: logs/spring-boot-logging.log
  level:
    com.piesat.kettleScheduler: debug
#    org:
#      springframework:
#        security: info


# 数据源配置
spring:
  datasource:
    #数据源配置-本地
#    url: jdbc:mysql://127.0.0.1:3306/kettle-scheduler-nmtest?useUnicode=true&characterEncoding=utf-8&useSSL=true
#    url: jdbc:mysql://127.0.0.1:3306/kettle-scheduler-nmtest?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    url: jdbc:mysql://121.36.24.29:3360/kettle-scheduler?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&useSSL=true
#    url: jdbc:mysql://127.0.0.1:3306/kettle-scheduler-nmtest?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=true
#    url: jdbc:mysql://127.0.0.1:3306/climate_modification?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: pieaccountC
    password: Piesat@123
    driver-class-name: com.mysql.jdbc.Driver


#jdbc:
#  driver: com.mysql.jdbc.Driver
#  url: jdbc:mysql://127.0.0.1:3306/kettle-scheduler-nmtest?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
#  username: root
#  password: 123456

#面向行业用户共享服务 ip
idata:
  url: http://121.36.14.224:8085/

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.piesat.kettlescheduler.model
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #SQL语句控制台打印


